//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.22 at 02:40:52 PM CEST 
//


package mx.randalf.archive.info;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.randalf.archive.info package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.randalf.archive.info
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link Archive }
     * 
     */
    public Archive createArchive() {
        return new Archive();
    }

    /**
     * Create an instance of {@link Type.Digest }
     * 
     */
    public Type.Digest createTypeDigest() {
        return new Type.Digest();
    }

    /**
     * Create an instance of {@link Type.Format }
     * 
     */
    public Type.Format createTypeFormat() {
        return new Type.Format();
    }

    /**
     * Create an instance of {@link Type.Image }
     * 
     */
    public Type.Image createTypeImage() {
        return new Type.Image();
    }

}
