//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.22 at 02:40:52 PM CEST 
//


package mx.randalf.archive.info;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xmltype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="xmltype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="mets"/>
 *     &lt;enumeration value="mag"/>
 *     &lt;enumeration value="premis"/>
 *     &lt;enumeration value="agent"/>
 *     &lt;enumeration value="rights"/>
 *     &lt;enumeration value="bagit"/>
 *     &lt;enumeration value="warc"/>
 *     &lt;enumeration value="event"/>
 *     &lt;enumeration value="registro"/>
 *     &lt;enumeration value="warc dc"/>
 *     &lt;enumeration value="mrc"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "xmltype")
@XmlEnum
public enum Xmltype {

    @XmlEnumValue("mets")
    METS("mets"),
    @XmlEnumValue("mag")
    MAG("mag"),
    @XmlEnumValue("premis")
    PREMIS("premis"),
    @XmlEnumValue("agent")
    AGENT("agent"),
    @XmlEnumValue("rights")
    RIGHTS("rights"),
    @XmlEnumValue("bagit")
    BAGIT("bagit"),
    @XmlEnumValue("warc")
    WARC("warc"),
    @XmlEnumValue("event")
    EVENT("event"),
    @XmlEnumValue("registro")
    REGISTRO("registro"),
    @XmlEnumValue("warc dc")
    WARC_DC("warc dc"),
    @XmlEnumValue("mrc")
    MRC("mrc");
    private final String value;

    Xmltype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Xmltype fromValue(String v) {
        for (Xmltype c: Xmltype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
